# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Max's Musings
email: maxmelnick@gmail.com
description: >
  My experience learning data science in NYC
#logo: "assets/images/logo.jpg"
logo: "assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maxmelnick.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Max Melnick'
bio: >
  I am passionate about creating technology products, sports / fitness, travel, cooking, and learning new things.
author_image: "assets/images/author.jpg"
#twitter_username: maxmelnick
github_username: maxmelnick

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
